server:
  port: 8002
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.test.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   application:
    name: springcloud-user 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://localhost:7001/eureka   
  instance:
    instance-id: springcloud-user-8002 
    ip-address: 192.168.1.2 #直接制定具体的ip地址 需要配置prefer-ip-address: true 才会生效
    prefer-ip-address: true #在eureka页面显示具体服务的IP地址，如果配置了   ip-address 则以ip-address为准
             
info: 
  app.name: springcloud-test
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


